### ISSUE TITLE
Need to include SciPy as one of the dependencies in the config.yml/requirements.txt file

### ISSUE THREAD

**Issue by waffledood** [nwjbrandon/ME5406-Project2#15]
As Savitzky-Golay filters are used to smoothen out the error plots, the SciPy library is a required dependency.

To include in the config.yml/requirements.txt file!

**Comment by nwjbrandon** [comment]
Included in the requirements.txt
https://github.com/nwjbrandon/ME5406-Project2/blob/master/requirements.txt

**Comment by waffledood** [comment]
alright great!
